[package]
name = "secret"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["George Muscat"]
license = "MIT"
description = "A simple package to redact text in rendered files."
keywords = ["redact", "secret"]